name: Build Armbian
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "deb http://deb.debian.org/debian trixie main" | sudo tee /etc/apt/sources.list.d/trixie.list
          sudo apt update
          sudo apt install -y -t trixie mkbootimg
          sudo rm /etc/apt/sources.list.d/trixie.list
          sudo apt update

      - uses: actions/checkout@v4

      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "dg-svr-865-tiny"
          armbian_release: "trixie"
          armbian_target: "build"
          armbian_ui: "minimal"
          armbian_runner_clean: "yes"

      - uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: output/images/*.img*
